### PR TITLE
process based parallelism.

### PR DESCRIPTION
**Pull request by bolshoydi**
merge conflict repaired. Tested using:

-  python 2.7.12 x64 GDAL 2.0.2. 
- python 3.4.4 x64 GDAL 2.0.2. 
- python 2.7.10 x32 GDAL 2.0.2.

On OS:

- win7 x64 core i7 8 CPU
- win10 x64 core i5-3210m 2.5GHz 4CPU (notebook\laptop)

### CODE REVIEW

**Comment by roblabs** [comment]
Very fast!! 

Tested with

* macOS 10.12.3
* Python 2.7.12, 
* GDAL 2.1.2, released 2016/10/24

**Comment by roblabs** [comment]
@bolshoydi,  I created PR https://github.com/pramsey/gdal2tilesp/pull/5 so that your changes go into the original repo that I forked from.

**Comment by bolshoydi** [comment]
@roblabs nice to hear this!!!! the next step i would like to create gdal2mbtilesp script with multiprocessing support

**Comment by roblabs** [comment]
@bolshoydi, are you aware of this project for creating `.mbtiles`?   I use it in conjunction with `gdal2tiles` for creating my final file.

https://github.com/mapbox/mbutil

**Comment by bolshoydi** [comment]
@roblabs yes, i know. Now i'm using gdal2tilesp to create tiles, then i use mbutil to create mbtiles. When input raster of small size (less 500Mb) everything fine and speed of loading images to mbtiles impressive, but when you load big amount of tiles (in my case 2.86Gb vrt of jpeg from 12 up to 21 zoom level made about 1.2millions of tiles) speed of loading (inserting) tiles into mbtiles became slow down from 2000 to 100 tiles / sec after 70,000 tiles inserted. My 8 CPUs were generating tiles for 5 hours + 5 hours of loading this tiles into mbtiles. I also tried different PRAGMA options to increase speed of tiles insertion. but nothing helps. So, i decided to combine both gdal2tilesp and mbutil scripts to write tiles directly into mbtiles.

**Pull request merged**
